### ISSUE TITLE
saying theres a syntax error when there is not

### ISSUE THREAD

**Issue by nathan545x** [Ruin9999/minecraft-bot#1]
SyntaxError: C:\Users\Pippa\Desktop\MCAI\minecraft-bot-main\config.json: Unexpected token : in JSON at position 13
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\Pippa\Desktop\MCAI\minecraft-bot-main\index.js:16:87)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)

**Comment by Ruin9999** [comment]
Let me check this out. Both your email and password are in the SS though just fyi

**Comment by nathan545x** [comment]
It’s just one of my ALTS so it don’t matter too much but I’ll change the password thanks for telling me I didn’t even knowtes

**Comment by Ruin9999** [comment]
Start the config file with "{" and end it with a "}".

In the end the file should look like this.

```
{
"botUsername" : "<username>",
"botPassword" : "<password>",
"server" : "<server>",
"serverPort" : "<port>",
"discordToken" : "<token>",
"discordPrefix" : "<prefix>"
}
```

**Comment by Ruin9999** [comment]
This should fix it :)

**Comment by nathan545x** [comment]
Yep thank you, I’m a idiot I didn’t relise something that simple lol

**Comment by Ruin9999** [comment]
Glad I could help :) Do feel free to hmu if you have any other issues/questions or feedback!
